spring.application.name=anuncios
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/anuncios_database}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}

security.token.secret=secret

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


endpoint.front = http://localhost:4200