spring.application.name=anuncios

spring.datasource.url=jdbc:mysql://localhost:3306/GPMS?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Ativar o log de SQL para visualizar as queries executadas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

